=== AsmaGargouri/Android-Project/sps_ips_android/ant/build.properties.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Mrad (MradFamily) -->
<!--DTD generated by XML Spy v4.1 U (http://www.xmlspy.com)-->

<!ELEMENT prop (tasks-username,application, build)>
<!ELEMENT tasks-username (#PCDATA)>
<!ELEMENT application (target)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT build (process, environment,jars,sdk_path)>
<!ELEMENT process (location, compiler)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT compiler (encoding,source, optimize, debug)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT optimize (#PCDATA)>
<!ELEMENT debug (#PCDATA)>
<!ELEMENT environment (#PCDATA)>
<!ELEMENT jars (#PCDATA)>
<!ELEMENT sdk_path (#PCDATA)>

=== AsmaGargouri/Android-Project/sps_ips_android/ant/sahbi/build.properties.xml
<?xml version="1.0"?>
<!DOCTYPE prop SYSTEM "../build.properties.dtd">
<prop>
  <tasks-username>SGA</tasks-username>
  <application>
 		<target>android-7</target>
  </application>
  <build>
    <process>
      <location>E:/projects/Mobile/SPS_IPS/sps_ips/dist</location>
      <compiler>
      	<encoding>UTF-8</encoding>
        <source>1.5</source>
        <optimize>off</optimize>
        <debug>on</debug>
      </compiler>
    </process>
    <environment>DEV</environment>
	 <jars>E:/projects/Mobile/SPS_IPS/sps_ips_android_utils/lib</jars>
	 <sdk_path>E:/documents/Mobile/adt-bundle-windows-x86-20140321</sdk_path>
  </build>
</prop>
